export const PLAY_VIDEO = "PLAY_VIDEO";
export const STOP_VIDEO = "STOP_VIDEO";

export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILED = "FETCH_DATA_FAILED";

export const CHANGE_LANG = "CHANGE_LANG";

export const LOADER_LOADING = "LOADER_LOADING";
export const CONTENT_LOADED = "CONTENT_LOADED";
export const LOADER_VISIBLE = "LOADER_VISIBLE";
